server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enrich?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/auth
          jwk-set-uri: http://localhost:8080/realms/auth/protocol/openid-connect/certs

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: "classpath:repository/*.xml"